# syntax=docker/dockerfile:experimental
  FROM alexosousa/acr:1.0 
  # nginx:latest
  # RUN apt-get update 
  WORKDIR /app
  COPY . /usr/share/nginx/html
  # RUN 
  # CMD ["nginx", "app/index.html"]
  EXPOSE 80